CREATE TABLE IF NOT EXISTS lots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lot_number VARCHAR(100) NOT NULL UNIQUE,
  target_qty INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lot_operations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lot_id INT NOT NULL,
  op_name VARCHAR(120) NOT NULL,
  rate_per_piece DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (lot_id) REFERENCES lots(id) ON DELETE CASCADE
);
